# For more information see: https://github.com/denoland/setup-deno

name: Build Binaries

on:
  push:
    tags:
    - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup repo
      uses: actions/checkout@v2
      
    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x

    - name: Build create_template Windows
      run: deno compile --allow-read --allow-write --allow-net --target x86_64-pc-windows-msvc -o create_template create_template.ts
      
    - name: Build create_template MacOS
      run: deno compile --allow-read --allow-write --allow-net --target x86_64-apple-darwin -o create_template create_template.ts
      
    - name: Build bundle Windows
      run: deno compile --allow-read --allow-write --allow-net --target x86_64-pc-windows-msvc -o bundle bundle.ts
      
    - name: Build bundle MacOS
      run: deno compile --allow-read --allow-write --allow-net --target x86_64-apple-darwin -o bundle bundle.ts
      
    - name: Relase
      uses: softprops/action-gh-release@v1
      with:
        files: |
          create_template.exe
          create_template
          bundle.exe
          bundle
